### ISSUE TITLE
Spring Engine and Springlobby crash when I put Scened-Core.sdd in games folder

### ISSUE THREAD

**Issue by Lowdive** [gajop/Scened-Core#106]
I just put it there and then whenever I want to start springlobby or spring engine they crash
if I remove it, then everything starts normally.
http://pastebin.com/uTnWhdQL

**Comment by Lowdive** [comment]
hmm still the same, I checked the packages dir, it had a lot of stuff I guess I saved some scenarios there by accident or something, I deleted all, packages is empty now and it still hangs on it, now with engine 101
http://pastebin.com/8M9GDLtG

**Comment by gajop** [comment]
According to the engine devs, you should try using the newest engine,
otherwise stack translate (http://stacktranslate.springrts.com/) won't work
and I won't be able to tell what's the issue.

2016-06-27 0:45 GMT+09:00 Elí Santiago <notifications@github.com>:

**Comment by Lowdive** [comment]
101.0.1-367-g9ba9e97 develop is the one I used on that last infolog... is there a newer engine?

**Comment by gajop** [comment]
Yes, see https://springrts.com/dl/buildbot/default/develop/

2016-06-27 2:10 GMT+09:00 Elí Santiago <notifications@github.com>:

**Comment by Lowdive** [comment]
Got'cha, here you go, this one works with stacktrace:
http://pastebin.com/QR9uL0Bf

**Comment by gajop** [comment]
Reported to mantis https://springrts.com/mantis/view.php?id=5288

**Comment by gajop** [comment]
Actually it seems that you aren't getting a crash but rather a "Hang", which means that Spring is taking a while to cache all your game and map archives.
I suggest you wait a bit or reduce the number of archives before trying again.

**Comment by Lowdive** [comment]
Indeed, I just left my computer there for a while (5-10min) and the engine
was on after that.
However that's very weird, it's never happened to me before, and it only
happens when scened-core is in games dir.
But the issue is resolved anyways. Thank you for the support.

On Mon, Jun 27, 2016 at 9:28 AM, Gajo Petrovic <notifications@github.com>
wrote:

> Actually it seems that you aren't getting a crash but rather a "Hang",
> which means that Spring is taking a while to cache all your game and map
> archives.
> I suggest you wait a bit or reduce the number of archives before trying
> again.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/gajop/Scened-Core/issues/106#issuecomment-228761839>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFWtfb7XZRG3IJpI2ZEqNYrnkXCCyqqbks5qP94CgaJpZM4I-k4I>
> .
>



-- 
José Elí Santiago Rodríguez.
Disponibilidad de Horario.
<https://www.google.com/calendar/embed?src=elisantiago.4e%40gmail.com&ctz=America/Mexico_City&mode=Week>

**Comment by gajop** [comment]
The caching might be slow (for whatever reasons) because there is a lot of big image files in Scened, although if you used a new engine, all files have to be cached (each engine requires recaching). 
This is not something I'll be optimizing in the near future, so marking this as solved.
